kind: Template
apiVersion: v1
metadata:
  name: deploy-mserv-java-springboot
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:${APP_VERSION}.${APP_BUILDID}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ubi8-openjdk-8:1.3
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers: []
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      build: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: false
  status: {}
parameters:
- name: APP_NAME
  required: true
- name: APP_NAMESPACE
  required: true
- name: APP_VERSION
  required: true
- name: APP_BUILDID
  required: true